### PR TITLE
Change terminology from AES-CM to AES-CTR

### PR DESCRIPTION
**Pull request by beurdouche**
I wasn't sure if CM was meant for "Counter Mode", if so, I thought using the standard terminology would be better... : )

### CODE REVIEW

**Comment by FredericJacobs** [comment]
I also originally got very confused by the CM acronym so definitely suggest taking the change.

**Review by youennf — APPROVED** [review]
LGTM.
This might conflict with https://github.com/sframe-wg/sframe/pull/68 depending on which PR gets merged first.

**Comment by youennf** [comment]
@beurdouche, would you be able to rebase your commit?

**Comment by beurdouche** [comment]
@youennf Should be good now. Note that I did not update the label in `derive_subkeys(sframe_key)` to avoid affecting the test vectors.

**Review by bifurcation — APPROVED** [review]
This PR looks good to me.  I agree with the terminology change and the changes to the known-answer test generator.  I re-ran the known-answer test generator locally and confirmed that it produced the test vectors in the PR.

**Pull request merged**
