### PR TITLE
Pictures!

### PR DESCRIPTION
**Pull request by martinthomson**
Some modest tweaking was necessary, but the result should be nicer.

Also, update the Makefile

### CODE REVIEW

**Comment by bifurcation** [comment]
@martinthomson is there a way to see how this renders?

**Comment by martinthomson** [comment]
If you had CI enabled, there would be a copy attached to this pull request.  I can upload HTML in a zip file though (there are too many pictures for screenshots).

[draft-omara-sframe.zip](https://github.com/eomara/sframe/files/8227668/draft-omara-sframe.zip)

**Comment by bifurcation** [comment]
I suppose that's something to fix once we get moved over to the WG repo.

**Comment by martinthomson** [comment]
The makefile changes are necessary to have this work.  I've added some more changes that will ensure that a local build works (assuming that you have the basic prerequisites installed).

**Review by youennf — APPROVED** [review]
I run this locally and this looks good to me.

**Pull request merged**
